sudo: 'required'

language: node_js
node_js:
  - 14
services:
  - docker

before_script:
  - echo "Udagram Image Filtering Application"

script:
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend bunya017/udagram-frontend:v1
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed bunya017/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user bunya017/udagram-api-user:v1
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy bunya017/reverseproxy:v1

after_script:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push bunya017/udagram-api-feed:v1
  - docker push bunya017/udagram-api-user:v1
  - docker push bunya017/udagram-frontend:v1
  - docker push bunya017/reverseproxy:v1
